env:
  TERM: xterm-256color

window:
  padding:
    x: 12
    y: 7
  decorations: none
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 0.90

font:
  normal:
    family: Victor Mono
    style: Medium
  bold:
    family: Victor Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Medium Italic
  bold_italic:
    family: Victor Mono
    style: Bold Italic
  glyph_offset:
    x: 0
    y: 2
  size: 14.0
draw_bold_text_with_bright_colors: true

cursor:
  blink_interval: 500
  
live_config_reload: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  - { mouse: Right,  action: Copy }

key_bindings:
  # Fix broken terminal
  # Ctrl-;      => F4
  # Ctrl-Return => F5
  # Ctrl-i      => F6
  # Ctrl-,      => F10
  # Ctrl-.      => F11
  - { key: Semicolon,  mods: Control,        chars: "\x1bOS" }
  - { key: Return,     mods: Control,        chars: "\x1b[15~" }
  - { key: I,          mods: Control,        chars: "\x1b[17~" }
  - { key: Comma,      mods: Control,        chars: "\x1b[21~" }
  - { key: Period,     mods: Control,        chars: "\x1b[23~" }
