# Anything except <space>, <tab>, =, {}
{{alias}}
# Shadowsocks proxy
socks5 = +forward-override{forward-socks5 127.0.0.1:1087 .}
# Direct
direct = +forward-override{forward .}
# NeteaseMusic
neteasemusic = +forward-override{forward 127.0.0.1:10001}

{socks5}
/
{direct}
.*.cn
.126.com
.126.net
.58.com
.64clouds.com
.acgvideo.com
.aicdn.com
.aliapp.org
.alibaba.com
.alicdn.com
.alikunlun.com
.alikunlun.net
.alipay.com
.alipayobjects.com
.aliyun.com
.aliyuncs.com
.amap.com
.antfin.com
.antfin-inc.com
.apple.com
.baidu.com
.baiduyundns.com
.baiduyundns.net
.bdimg.com
.bdstatic.com
.bdydns.com
.bdydns.net
.beisen.com
.bilibili.com
.bilivideo.com
.bing.com
.bitbucket.org
.bosszhipin.com
.bwh88.net
.cdnjs.com
.cowtransfer.com
.csdn.net
.cstimer.net
.ctrip.com
.dangdang.com
.digitalocean.com
.dingtalkapps.com
.dingtalk.com
.dji.com
.douban.com
.doubanio.com
.douyin.com
.douyu.com
.ele.me
.etao.com
.feng.com
.fliggy.com
.gitee.com
.github.io
.githubassets.com
.guokr.com
.hdlsb.com
.huya.com
.iqiyi.com
.ithome.com
.jd.com
.jianshu.com
.jianshuapi.com
.jikipedia.com
.kuaidi100.com
.kugou.com
# .kuwo.cn
.lanzous.com
.le.com
.linkedin.com
.linode.com
.lizhi.fm
.meituan.com
.meizu.com
.mgtv.com
.miaopai.com
.mi.com
.miwifi.com
.mmstat.com
.msstatic.com
.mzstatic.com
.netease.com
.oneplus.com
.oursketch.com
.outlook.com
.pgyer.com
.pingwest.com
.polyfill.io
.pptv.com
.qcloud.com
.qichacha.com
.qq.com
.qyer.com
.shimo.im
.sina.com
.slack.com
.smartisan.com
.smzdm.com
.sogou.com
.sohu.com
.soku.com
.sspai.com
.suning.com
.taihe.com
.talkingdata.com
.taobaocdn.com
.taobao.com
.taobao.org
.tencent.com
.thetype.com
.tianyancha.com
.tmall.com
.toutiao.com
.tudou.com
.tuniu.com
.typeisbeautiful.com
.uisdc.com
.umeng.com
.undraw.co
.visualhunt.com
.vmall.com
.vultr.com
.wandoujia.com
.weather.com
.weibocdn.com
.weibo.com
.xdccpro.com
.xiami.com
.xiaomi.com
.xueqiu.com
.xunlei.com
.yinyuetai.com
.ykimg.com
.youdao.com
.youku.com
.yuque.com
.zhaopin.com
.zhihu.com
.zhimg.com
.zhipin.com

{neteasemusic}
# .music.126.net
.music.163.com
.interface.music.163.com
