packadd! coc.nvim
packadd! nvim-colorizer.lua
packadd! fzf | packadd! fzf.vim
packadd! vifm.vim
packadd! tcomment_vim
packadd! vim-textobj-user
packadd! vim-textobj-quotes
packadd! vim-textobj-indent
packadd! vim-textobj-comment
packadd! vim-sneak
packadd! vim-easy-align
packadd! vim-surround
packadd! vim-fugitive
packadd! vim-repeat
packadd! vim-eunuch
packadd! vim-slime
packadd! vim-buftabline
packadd! vim-bujo
packadd! nvim-treesitter
