TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  # CTRL: CAPS and RETURN
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_CAPSLOCK
    TAP: KEY_BACKSPACE
    HOLD: KEY_LEFTCTRL
  # SHIFT: L_SHIFT and SLASH
  - KEY: KEY_LEFTSHIFT
    TAP: KEY_ESC
    HOLD: KEY_LEFTSHIFT
  - KEY: KEY_SLASH
    TAP: KEY_SLASH
    HOLD: KEY_RIGHTSHIFT
  # MOD1: L_ALT and R_ALT
  - KEY: KEY_LEFTALT
    TAP: KEY_MINUS
    HOLD: KEY_LEFTALT
  - KEY: KEY_RIGHTALT
    TAP: KEY_EQUAL
    HOLD: KEY_LEFTALT
  # MOD3: FN and R_SHIFT
  - KEY: KEY_INSERT
    TAP: KEY_INSERT
    HOLD: KEY_SYSRQ
  - KEY: KEY_RIGHTSHIFT
    TAP: KEY_RIGHTSHIFT
    HOLD: KEY_SYSRQ
  # MOD4: Unchanged
  - KEY: KEY_LEFTMETA
    TAP: KEY_KPEQUAL
    HOLD: KEY_LEFTMETA
  - KEY: KEY_RIGHTMETA
    TAP: [ KEY_RIGHTSHIFT, KEY_6 ]
    HOLD: KEY_RIGHTMETA
  # EXTRAS
  - KEY: KEY_ESC
    TAP: KEY_F13
    HOLD: []
