TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  # CTRL: CAPS and RETURN
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_CAPSLOCK
    TAP: KEY_BACKSPACE
    HOLD: KEY_LEFTCTRL
  # R_SHIFT: SLASH
  - KEY: KEY_SLASH
    TAP: KEY_SLASH
    HOLD: KEY_RIGHTSHIFT
  # MOD1: L_ALT and R_ALT
  - KEY: KEY_LEFTALT
    TAP: KEY_LEFTALT
    HOLD: KEY_LEFTALT
  - KEY: KEY_RIGHTALT
    TAP: [ KEY_LEFTMETA, KEY_F6, ]
    HOLD: KEY_LEFTALT
  # MOD3: FN and R_SHIFT
  - KEY: KEY_INSERT
    TAP: KEY_INSERT
    HOLD: KEY_SYSRQ
  - KEY: KEY_RIGHTSHIFT
    TAP: KEY_INSERT
    HOLD: KEY_SYSRQ
  # MOD4: L_META and R_META
  - KEY: KEY_LEFTMETA
    TAP: KEY_MINUS
    HOLD: KEY_LEFTMETA
  - KEY: KEY_RIGHTMETA
    TAP: KEY_EQUAL
    HOLD: KEY_RIGHTMETA
  # MOD3 + MOD4: L_CTRL
  - KEY: KEY_LEFTCTRL
    TAP: KEY_ESC
    HOLD: [ KEY_SYSRQ, KEY_LEFTMETA, ]
