TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_SLASH
    TAP: KEY_SLASH
    HOLD: KEY_RIGHTSHIFT
  - KEY: KEY_CAPSLOCK
    TAP: KEY_BACKSPACE
    HOLD: KEY_LEFTCTRL
  - KEY: KEY_INSERT
    TAP: KEY_ESC
    HOLD: KEY_INSERT
  - KEY: KEY_DELETE
    TAP: KEY_DELETE
    HOLD: KEY_INSERT
  - KEY: KEY_LEFTMETA
    TAP: KEY_MINUS
    HOLD: KEY_LEFTMETA
  - KEY: KEY_RIGHTMETA
    TAP: KEY_EQUAL
    HOLD: KEY_RIGHTMETA
