if has('nvim')
  packadd! nvim-lsp
  packadd! deoplete.nvim
  packadd! deoplete-lsp
  packadd! nvim-colorizer.lua
endif
packadd! fzf
packadd! fzf.vim
packadd! vifm.vim
packadd! targets.vim
packadd! ultisnips
packadd! tcomment_vim
packadd! vim-surround
packadd! vim-fugitive
packadd! vim-repeat
packadd! vim-eunuch
packadd! vim-sneak
packadd! vim-easy-align
packadd! vim-markdown
