#!/bin/sh
bspc rule -r "*"

pgrep bspswallow || bspswallow &
pgrep bspsubscribe || bspsubscribe &

bspc monitor ^1 -d Main
bspc monitor ^2 -d Dev Web Doc Msc Vid PDF Art

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Brave-browser:crx_cinhimbnkkaeohfgghhklpknlkffjgod desktop='^5' state=tiled follow=on
bspc rule -a brave2nd desktop='^1' state=fullscreen follow=on
bspc rule -a obs desktop='^1' state=fullscreen follow=on
bspc rule -a ktouch state=floating
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Emacs desktop='^4' state=fullscreen follow=on
# bspc rule -a Screenkey manage=off
