#! /bin/sh
bspc rule -r "*"

launchPolybar &
xwallpaper --zoom ~/Pictures/Wallpaper/Fuji-mountain.jpg &
picom &

bspc monitor DP-0 -d Dev Web Doc Music aa bb cc

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a netease-cloud-music-gtk desktop='^4' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

(bspc subscribe node_add | while read add; do
[[ $(bspc wm -g | awk -F ':' '{print $(NF-2)}') == 'LM' ]] && bspc desktop -l next; done &)

(sleep 3; npx --cache ~/.cache/npm @nondanee/unblockneteasemusic -p 10001:10002 &)
