# Anything except <space>, <tab>, =, {}
{{alias}}
# Shadowsocks proxy
socks5 = +forward-override{forward-socks5 127.0.0.1:1087 .}
# Direct
direct = +forward-override{forward .}
# NeteaseMusic
neteasemusic = +forward-override{forward 127.0.0.1:10001}

{socks5}
/
{direct}
.126.com
.126.net
.36kr.com
.56.com
.58.com
.58pic.com
.64clouds.com
.699pic.com
.acgvideo.com
.aicdn.com
.aliapp.org
.alibaba.com
.alicdn.com
.alikunlun.com
.alikunlun.net
.alipay.com
.alipayobjects.com
.aliyun.com
.aliyuncs.com
.amap.com
.ant.design
.antfin.com
.antfin-inc.com
.appinn.com
.appinn.net
.apple.com
.baidu.com
.baiduyundns.com
.baiduyundns.net
.bdimg.com
.bdstatic.com
.bdydns.com
.bdydns.net
.beisen.com
.bible.com
.bilibili.
.bilivideo.com
.bing.com
.bitbucket.org
.bluedoc.io
.bootcss.com
.bosszhipin.com
.btsync.org
.bwh88.net
.cctv.com
.cdnjs.com
.cdntip.com
.chainnews.com
.chinaz.com
.chongdiantou.com
.clouddn.com
.cnbeta.com
.cnzz.com
.coloros.com
.cowtransfer.com
.csdn.net
.cstimer.net
.ctrip.com
.dangdang.com
.digitalocean.com
.dingtalkapps.com
.dingtalk.com
.dji.com
.douban.
.doubanio.com
.douyin.com
.douyu.com
.draw.io
.ele.me
.etao.com
.ewei.com
.feng.com
.fir.im
.fliggy.com
.foundertype.com
.gitee.com
.github.io
.googletagmanager.com
.gratisography.com
.growingio.com
.gtimg.com
.guokr.com
.hao123.com
.haosou.com
.hdb.com
.hdlsb.com
.huaban.com
.huya.com
.icloud.com
.ifeng.com
.iguoguo.net
.iina.io
.imooc.com
.infoq.com
.intercomcdn.com
.ipip.net
.iqiyi.com
.ithome.com
.itjuzi.com
.jd.com
.jianshu.
.jianshuapi.com
.jikipedia.com
.kf5.com
.kuaidi100.com
.kuaishou.com
.kugou.com
.lanhuapp.com
.lanzous.com
.le.com
.liantu.com
.linkedin.com
.linode.com
.lizhi.fm
.lkkdesign.com
.lvmama.com
.ly.com
.macrr.com
.magi.com
.meituan.com
.meizu.com
.mgtv.com
.miaopai.com
.mi.com
.microbit.org
.microsoft.com
.microsoftedgeinsider.com
.minapp.com
.miwifi.com
.mmstat.com
.msstatic.com
.mu6.me
.myqcloud.com
.mzstatic.com
.netease.com
.nobook.com
.now.sh
.oneplus.com
.oppo.com
.oursketch.com
.outlook.com
.panda.tv
.panduoduo.net
.pexels.com
.pgyer.com
.pingwest.com
.pluwen.com
.polyfill.io
.pptv.com
.processon.com
.qbox.me
.qcloud.com
.qhimg.com
.qichacha.com
.qiniudn.com
.qiniudns.com
.qiniuts.com
.qiuziti.com
.qq.com
.qyer.com
.sc115.com
.shimo.im
.sina.com
.slack.com
.smartisan.com
.smzdm.com
.sogou.com
.sohu.com
.soku.com
.soso.com
.sspai.com
.suning.com
.taihe.com
.talkingdata.com
.taobaocdn.com
.taobao.com
.tcdn.qq.com
.tencent.com
.thetype.com
.tianyancha.com
.tmall.com
.toutiao.com
.trontv.com
.tuchong.com
.tudou.com
.tuniu.com
.typeisbeautiful.com
.ucweb.com
.uedna.com
.uisdc.com
.umeng.com
.undraw.co
.visualhunt.com
.vmall.com
.vultr.com
.wallhaven.cc
.wandoujia.com
.weather.com
.weibocdn.com
.weibo.com
.woshipm.com
.xdccpro.com
.xiami.com
.xiaomi.com
.xiaotu.io
.xueqiu.com
.xunlei.com
.xywy.com
.yinxiang.com
.yinyuetai.com
.ykimg.com
.youdao.com
.youku.com
.yunjiasu-cdn.net
.yuque.com
.zanmeishi.com
.zhaopin.com
.zhihu.com
.zhimg.com
.zhipin.com
.zhongguose.com

{neteasemusic}
.music.163.com
