# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"
alias c="fzf-cd"
alias d="gio trash"
alias f="vifmrun ."
alias g="git"
alias s="sudo"
alias t="tmux-automation"
alias v='nvim -c "let g:tty='\''$(tty)'\''"'
alias ka="killall"
alias la="ls -Flha --group-directories-first --color=auto"
alias ls="ls -a --group-directories-first --color=auto"
alias md="mkdir -p"
alias yd="youtube-dl --write-sub --write-auto-sub -o '~/Desktop/%(title)s-%(id)s.%(ext)s'"
alias ydl="youtube-dl --yes-playlist --write-sub --write-auto-sub -o '~/Desktop/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"
alias -g G="| rg"
alias -g B="| bat"
alias -g W="| wc -l"
