ZDOTDIR="/home/alex/.config/zsh"
HISTFILE="/home/alex/.local/share/zsh/history"
HISTSIZE=10000; SAVEHIST=10000

# Following aliases are available in nvim since in .zshenv
alias twf="twf --bind='h::tree:close,l::tree:open' --previewCmd='bat -p --color=always {}'"
