ZDOTDIR="/home/alex/.config/zsh"
# Following aliases are available in nvim since in .zshenv
alias twf="twf --bind='n::tree:next,e::tree:prev,h::tree:close,i::tree:open,ctrl-n::preview:down,ctrl-e::preview:up' --previewCmd='bat -p --color=always {}'"
