#!/bin/bash
/Users/alex/bin/ariaTracker;
killall aria2c;
kill $(ps aux | grep '[a]pp.js\ -p\ 10001' | awk '{print $2}'); 
/usr/local/aria2/bin/aria2c -D --conf-path=/Users/alex/.config/aria2/aria2.conf; 
/usr/local/bin/node /Users/alex/dev/apps/UnblockNeteaseMusic/app.js -p 10001:10002
