#!/bin/sh
easystroke --config-dir $XDG_CONFIG_HOME/easystroke &
remaps &
xrdb -merge $XDG_CONFIG_HOME/X11/xresources
sxhkd &
aria2c --input-file=/home/alex/.cache/aria2/aria2.session &
deadd-notification-center &
privoxy --no-daemon ~/.config/privoxy/config &
fcitx &
flameshot &

# Finally, window manager
exec bspwm
# ssh-agent bspwm
