#!/bin/sh
. ~/.config/zsh/system/variable.zsh
xrdb -merge ~/.config/x11/xresources &

easystroke --config-dir ~/.config/easystroke &
deadd-notification-center &
fcitx5 &
flameshot &
~/.local/bin/x/autolock &
redshift -b 1.0:0.7 -l 30.59:114.27 &
picom --experimental-backends &
xwallpaper --output $DISPLAY_DEVICE --zoom $WALLPAPER &
xsetroot -cursor_name left_ptr &
mpDris2 --music-dir=~/Music &

exec awesome
