#!/bin/sh
export DISPLAY_DEVICE=$(xrandr | awk '/ connected/{print $1}')
xrdb -merge ~/.config/x11/xresources &

easystroke --config-dir ~/.config/easystroke &
sxhkd -m 1 &
deadd-notification-center &
fcitx5 &
flameshot &
autolock &
redshift &
picom --experimental-backends &
xwallpaper --output $DISPLAY_DEVICE --zoom $WALLPAPER &
polybar bar &
xsetroot -cursor_name left_ptr &

exec bspwm
