#!/bin/sh
xrdb -merge ~/.config/x11/xresources &
easystroke --config-dir ~/.config/easystroke &
fcitx5 &
flameshot &
autolock &
redshift -b 1.0:0.7 -l 30.59:114.27 &
picom --experimental-backends &
xsetroot -cursor_name left_ptr &
mpd &
mpDris2 --music-dir=~/Music &

exec awesome
