#!/bin/sh
d1=$1
size=${2:-40}
case $d1 in
  left)   d2=right;  dx=-$size; dy=0;;
  bottom) d2=top;    dx=0;      dy=$size;;
  top)    d2=bottom; dx=0;      dy=-$size;;
  right)  d2=left;   dx=$size;  dy=0;;
esac
bspc node --resize $d1 $dx $dy || bspc node --resize $d2 $dx $dy
