#!/bin/bash
direction=$1
size=${2:-'40'}
wid=$(xdotool getactivewindow)
wininfo=$(xwininfo -id "$wid")
width=$(echo "$wininfo" | awk '/Width/ {print $2}')
height=$(echo "$wininfo" | awk '/Height/ {print $2}')
case $direction in
	left)
		# bspc node @east -r -40 || bspc node @west -r -40
		bspc node -z left -$size 0
		win_width=$(xwininfo -id "$wid" | awk '/Width/ {print $2}')
		[[ $width == $win_width ]] && bspc node -z right -$size 0
		;;
	down)
		# bspc node @south -r +35 || bspc node @north -r +35
		bspc node -z bottom 0 +$size
		win_height=$(xwininfo -id "$wid" | awk '/Height/ {print $2}')
		[[ $height == $win_height ]] && bspc node -z top 0 +$size
		;;
	up)
		# bspc node @north -r -35 || bspc node @south -r -35
		bspc node -z top 0 -$size
		win_height=$(xwininfo -id "$wid" | awk '/Height/ {print $2}')
		[[ $height == $win_height ]] && bspc node -z bottom 0 -$size
		;;
	right)
		# bspc node @west -r +40 || bspc node @east -r +40
		bspc node -z right +$size 0
		win_width=$(xwininfo -id "$wid" | awk '/Width/ {print $2}')
		[[ $width == $win_width ]] && bspc node -z left +$size 0
		;;
esac
