#!/bin/sh
dir_wm=$1
run_from_vim=$2

wm_navigation() { bspc node -f $dir_wm.local; }
tmux_navigation() {
  case "$1" in
    west)  dir_tmux="L"; dir_check="left";;
    south) dir_tmux="D"; dir_check="bottom";;
    north) dir_tmux="U"; dir_check="top";;
    east)  dir_tmux="R"; dir_check="right";;
  esac
  _pane_at_edge() { [ "$(tmux display -p "#{pane_at_$dir_check}")" == 1 ]; }
  _tmux_navigation() { tmux selectp -$dir_tmux; }
  $(_pane_at_edge) && wm_navigation || _tmux_navigation
}
window_is_vim() { [ $(xdotool getwindowfocus getwindowname) == 'nvim' ] || return 1; }
window_is_tmux() {
  wid=$(xdotool getwindowfocus)
  w_pid=$(xprop -id $wid _NET_WM_PID | awk '{print $3}')
  grand_child_pid=$(pgrep -P $(pgrep -P $w_pid))
  curr_cmd=$(ps -o cmd= $grand_child_pid)
  [[ "$curr_cmd" == "tmux"* ]] && return 0 || return 1
}

case "$dir_wm" in
  west)  keysym="h";;
  south) keysym="j";;
  north) keysym="k";;
  east)  keysym="l";;
esac

"$run_from_vim" && { tmux_navigation $dir_wm; exit; }

if $(window_is_vim); then
  xvkbd -xsendevent -text "\C$keysym"
elif $(window_is_tmux); then
  tmux_navigation $dir_wm
else
  wm_navigation
fi
