#!/bin/sh
swallow_list=("mpv" "Sxiv" "Zathura")

swallow() {
  addedtodesktop=$2
  lasttermdesktop=$(bspc query -D -n last)
  swallowerid=$1
  swallowingid=$(bspc query -N -n last)
  skip_swallow=$(tr '[:upper:]' '[:lower:]' <<< ${swallow_list[@]})
  if [ "$addedtodesktop" = "$lasttermdesktop" ]; then
    [[ "${swallow_list[@]}" == *"$(__get_class "$swallowerid")"* ]] || return
    # don't swallow when launching outside terminal
    [[ "${skip_swallow[@]}" == *"$(__get_title "$swallowingid")"* ]] || return
    echo "$swallowerid $swallowingid" >> /tmp/swallowids
    bspc node "$swallowingid" --flag hidden=on
  fi
}

spit() {
  spitterid=$1
  spitterdesktop=$2
  grep "^$spitterid" /tmp/swallowids || return
  spittingid=$(grep "^$spitterid" /tmp/swallowids | head -n1 | awk '{print $2}')
  bspc node "$spittingid" --flag hidden=off
  termdesktop=$(bspc query -D -n "$spittingid")
  [ "$termdesktop" = "$spitterdesktop" ] || bspc node "$spittingid" -d "$spitterdesktop"
  bspc node "$spittingid" -f
  sed -i "/^$spitterid/d" /tmp/swallowids
}

bg_cleaner() { [[ $1 == "monocle" ]] && __hide_all_except $(__current) || __show_all; }

__hide_all_except() {
  for node in $(bspc query -N -n .local.window); do
    bspc node $node --flag hidden=on
  done
  bspc node $1 --flag hidden=off
}
__show_all() {
  [[ $(__focus) = *"- YouTube - Brave" ]] && return
  for node in $(bspc query -N -n .local.window); do
    bspc node $node --flag hidden=off
  done
  for node in $(awk '{print $2}' /tmp/swallowids); do
    bspc node $node --flag hidden=on
  done
}
__focus() { xdotool getwindowfocus getwindowname; }
__get_class() { xprop -id $1 WM_CLASS | cut -d '"' -f 4; }
__get_title() { xdotool getwindowname $1; }
__current() { bspc query -N -n focused; }
