#!/bin/sh
get_class() {
  [ -n "$1" ] && xprop -id "$1" | sed -n '/WM_CLASS\|WM_COMMAND/s/.*"\(.*\)".*/\1/p'
}

swallow() {
	addedtodesktop=$2
	lasttermdesktop=$(bspc query -D -n last)
	swallowerid=$1
	swallowingid=$(bspc query -N -n last)
	if [ "$addedtodesktop" = "$lasttermdesktop" ]; then
		cat ~/.config/bspwm/scripts/noswallow ~/.config/bspwm/scripts/terminals | grep "^$(get_class "$swallowerid")$" && return
		grep "^$(get_class "$swallowingid")$" ~/.config/bspwm/scripts/terminals || return
		echo "$swallowerid $swallowingid" >> /tmp/swallowids
		bspc node "$swallowingid" --flag hidden=on
	fi
}

spit() {
	spitterid=$1
	spitterdesktop=$2
	grep "^$spitterid" /tmp/swallowids || return
	spittingid=$(grep "^$spitterid" /tmp/swallowids | head -n1 | awk '{print $2}')
	bspc node "$spittingid" --flag hidden=off
	termdesktop=$(bspc query -D -n "$spittingid")
	[ "$termdesktop" = "$spitterdesktop" ] || bspc node "$spittingid" -d "$spitterdesktop"
	bspc node "$spittingid" -f
	sed -i "/^$spitterid/d" /tmp/swallowids
}

hideall(){
 for node in $(bspc query -N -n .local.window); do
   bspc node $node --flag hidden=on
 done
 bspc node $1 --flag hidden=off
}

unhideall(){
 for node in $(bspc query -N -n .local.window); do
   bspc node $node --flag hidden=off
 done
}

bspc subscribe node_add node_remove | while read event _ parent child_a child_r ; do
  case $event in
    node_add) swallow $child_r $parent;;
    node_remove) spit $child_a $parent;;
  esac
done &

bspc subscribe desktop_layout | while read _ _ _ layout; do
 current=$(bspc query -N -n focused)
 [[ $layout == "monocle" ]] && hideall $current || unhideall
done &
